var ADD_TODO = 'ADD_TODO';
var DELETE_TODO = 'DELETE_TODO';
var EDIT_TODO = 'EDIT_TODO';
var COMPLETE_TODO = 'COMPLETE_TODO';
var COMPLETE_ALL = 'COMPLETE_ALL';
var CLEAR_COMPLETED = 'CLEAR_COMPLETED';
